name: Bug Report
description: Create a report to help us improve
title: "[Affected functionality] Clear and concise summary, e.g. \"[Create news] 'Publish' button is not displayed on the 'Preview' page\""
labels: ["bug"]
assignees: []
body:
  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, browser, version, device (for mobile).
      placeholder: "Windows 10, Chrome 119, iPhone 12"
    validations:
      required: true

  - type: dropdown
    id: reproducible
    attributes:
      label: Reproducibility
      description: How often does the bug occur?
      options:
        - Always
        - Sometimes
        - Rarely
        - Unable to reproduce
    validations:
      required: true

  - type: input
    id: build
    attributes:
      label: Build / Commit
      description: Link or commit hash where the bug was found.
      placeholder: "commit 147fa44 from dev branch"
    validations:
      required: true

  - type: textarea
    id: preconditions
    attributes:
      label: Preconditions
      description: Actions or setup needed before reproducing the bug.
      placeholder: |
        Example:
        1. Create an item in the database:
           INSERT INTO table1 (column1, column2)
           VALUES (value1, value2);

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Exact steps to reproduce the issue.
      placeholder: |
        1. Go to "..."
        2. Click on "..."
        3. Scroll down to "..."

  - type: textarea
    id: actual
    attributes:
      label: Actual Result
      description: What actually happened (visible, missing, broken, etc.).
      placeholder: "Button is not displayed. See screenshot below."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Result
      description: What should have happened.
      placeholder: "Button should be displayed. See mock-up or screenshot."
    validations:
      required: true

  - type: textarea
    id: postconditions
    attributes:
      label: Postconditions
      description: Cleanup steps needed after reproducing the bug.
      placeholder: |
        Example:
        DELETE FROM table1 WHERE id=<item1_id>;

  - type: textarea
    id: references
    attributes:
      label: User Story and Test Case Links
      description: Links to related user stories, test cases, or documentation.
      placeholder: |
        User story #100
        [Test case](https://jira.softserve.academy/browse/100)

  - type: checkboxes
    id: labels
    attributes:
      label: Labels to Add
      description: Select applicable labels.
      options:
        - label: "Bug"
          required: true
        - label: "Priority: High"
        - label: "Priority: Medium"
        - label: "Priority: Low"
        - label: "Severity: Critical"
        - label: "Severity: Major"
        - label: "Severity: Minor"
        - label: "Type: UI"
        - label: "Type: Functional"
        - label: "Type: API"
