name: General Issue
description: Report a bug or suggest a new feature
labels: ["needs-triage"]
body:
  - type: textarea
    id: title
    attributes:
      label: 🧩 Title
      description: Short and clear description of the issue.
      placeholder: "Bug: login button not visible on mobile" 
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 📌 Description
      description: What is the problem or the task? Describe clearly.
      placeholder: "The 'Login' button is missing on screens smaller than 768px."
    validations:
      required: true

  - type: textarea
    id: goal
    attributes:
      label: 🎯 Goal / Expected Result
      description: What should be the final outcome?
      placeholder: "The 'Login' button should always be visible and usable on mobile devices."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🔍 Steps to Reproduce (for bugs)
      description: List steps so anyone can reproduce the issue.
      placeholder: |
        1. Go to the home page.
        2. Resize the screen to 375px width.
        3. Check if the "Login" button is visible.

  - type: checkboxes
    id: acceptance
    attributes:
      label: ✅ Acceptance Criteria
      description: Define clear conditions when the issue is done.
      options:
        - label: The issue is fixed or the feature is implemented as described.
        - label: Works across major browsers (Chrome, Firefox, Safari).
        - label: Tests are added/updated if applicable.
        - label: Code has passed review.

  - type: textarea
    id: additional
    attributes:
      label: 📂 Additional Info
      description: Add any extra details.
      placeholder: |
        - Screenshots / videos (for bugs)
        - Design / mockup link (for features)
        - Dependencies, risks, clarifications
