name: Feature Request
description: Suggest a new feature or improvement for the project
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!  
        Please fill in the sections below as clearly as possible.

  - type: input
    id: summary
    attributes:
      label: Short Summary
      description: Briefly describe the feature in one sentence.
      placeholder: "Example: Add dark mode option"

  - type: textarea
    id: problem
    attributes:
      label: Problem to Solve
      description: What problem or need does this feature address?
      placeholder: "Users have difficulty reading the interface in low light"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your idea for how the problem should be solved.
      placeholder: "Introduce a dark theme toggle in settings"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered other ways to solve this?
      placeholder: "Could use browser extensions, but they don't work well with our UI"

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What positive impact will this feature have?
      placeholder: "Improves accessibility and user comfort"

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - 🔴 High – needed urgently
        - 🟠 Medium – would be very useful
        - 🟡 Low – nice to have
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Any other details, links, or references.
      placeholder: "See similar feature in GitHub dark mode"
